Simplify logic a bit

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -131,16 +131,18 @@ jobs:
           BASENAME: ${{ steps.package.outputs.output-basename }}
         run: |
           if [ "$RUNNER_OS" = "macOS" ]; then
-            if [ -f "build/${BASENAME}.dmg" ]; then
-              echo "package_path=build/${BASENAME}.dmg" >> $GITHUB_OUTPUT
-            elif [ -f "build/${BASENAME}.zip" ]; then
-              echo "package_path=build/${BASENAME}.zip" >> $GITHUB_OUTPUT
-            else
-              echo "ERROR: No macOS package found"
-              exit 1
-            fi
+            for ext in dmg zip; do
+              if [ -f "build/${BASENAME}.${ext}" ]; then
+                echo "package_path=build/${BASENAME}.${ext}" >> $GITHUB_OUTPUT
+                exit 0
+              fi
+            done
+            
+            echo "ERROR: No macOS package found"
+            exit 1
           else
-            if !find build -maxdepth 1 -name "${BASENAME}*" | grep -q .; then
+            files=(build/${BASENAME}*)
+            if [ ! -e "${files[0]}" ]; then
               echo "ERROR: No package found"
               exit 1
             fi
